<?
require_once("{$_SERVER['DOCUMENT_ROOT']}/inc/funcs-hts.phtml");

function top($lines,$cond)
{
    global $title;

    $link = @mysql_connect("localhost", "kron", "KTNXBR");
    @mysql_select_db("KRON");
    $sql = "SELECT * FROM `page_counts` WHERE id $cond ORDER BY SQRT(RAND())*count/(".time()."-start+3600) DESC LIMIT $lines"; 
    $top = mysql_query ($sql) or  die ("Query failed, error ".mysql_errno().": ".mysql_error()."<BR>");

    for($i=0; $i<$lines; $i++)
    {
        $row = mysql_fetch_array($top);
        $title=$row['id'];

        if(preg_match("!^/forum/(\d+)/(\d+)!",$row['id'],$m))
        {
            $subdir=sprintf("%04d",intval($m[2]/100));
            $file=@file("{$_SERVER['DOCUMENT_ROOT']}/forum/Forum$m[1]/$subdir/".sprintf("%06d",$m[2]).".cgi");
            list($type,$x1,$replies,$author,$subj,$x2,$ico,$x3)=split("\|\|",$file[0]);
            $title=$subj;
        }
        else
        {
            if(preg_match("!^(/.*)\.phtml$!",$row['id'],$m))
                $file="{$_SERVER['DOCUMENT_ROOT']}$m[1].hts";
            if(preg_match("!^(/.*)\-\d+\.phtml$!",$row['id'],$m))
                $file="{$_SERVER['DOCUMENT_ROOT']}$m[1].hts";
            
            if(file_exists("$file"))
            {
                hts_load($file);
            }
        }
        $subject=strlen($title)>14 ? substr($title,0,15)."..." : $title;//wordwrap($title, 15, " ", 1);
        echo "&#183; <a title=\"$title; ".sprintf("%.1f",$row['count']/(time()-$row['start']+1)*86400)." заходов в сутки\" href=".$row['id'].">$subject</a><br>\n";
    }
    mysql_free_result($top);
    mysql_close($link);
}

?>
<h5>Авиабаза</h5>
<?top(10,"NOT LIKE '/forum%'")?>
<h5>Форумы</h5>
<?top(10,"LIKE '/forum%'");?>
