<?
    ini_set('default_charset','utf-8');

    @header('Content-Type: text/html; charset=utf-8');
    @header('Content-Language: ru');

    setlocale(LC_ALL, "ru_RU.utf8");
?>
with(document)
{
<?
    $nobanner=1;
    ob_start();
    include("topics.phtml");
    $file = split("\n",ob_get_contents());
    ob_end_clean();

    for($i=0;$i<sizeof($file);$i++)
    {
        $s=str_replace("\\","\\\\",$file[$i]);
        $s=str_replace("\"","\\\"",$s);
        $s=str_replace("\n"," ",$s);
        $s=str_replace("\r"," ",$s);
        echo "write(\"$s\");\n";
    }
?>
}